// Generated by https://quicktype.io

export interface AdjustAccountResponse {
	'soapenv:Envelope': SoapenvEnvelope;
}

export interface SoapenvEnvelope {
	$: SoapenvEnvelopeClass;
	'soapenv:Header': string[];
	'soapenv:Body': SoapenvBody[];
}

export interface SoapenvEnvelopeClass {
	'xmlns:soapenv': string;
}

export interface SoapenvBody {
	AdjustAccountResultMsg: AdjustAccountResultMsg[];
}

export interface AdjustAccountResultMsg {
	$: Purple;
	ResultHeader: ResultHeader[];
	AdjustAccountResult: AdjustAccountResult[];
}

export interface Purple {
	xmlns: string;
}

export interface AdjustAccountResult {
	$: Purple;
	AcctChgRec: AcctChgRec[];
	LifeCycleState: LifeCycleState[];
}

export interface AcctChgRec {
	$: Purple;
	CurrAcctBal: string[];
	ChgAcctBal: string[];
	CurrExpTime: string[];
	ChgExpTime: string[];
	AccountType: string[];
	AccountID: string[];
	MinMeasureId: string[];
}

export interface LifeCycleState {
	_: string;
	$: Purple;
}

export interface ResultHeader {
	$: Purple;
	CommandId: LifeCycleState[];
	Version: LifeCycleState[];
	TransactionId: LifeCycleState[];
	SequenceId: LifeCycleState[];
	ResultCode: LifeCycleState[];
	ResultDesc: LifeCycleState[];
}
