// Generated by https://quicktype.io

export interface IntegrationEnquiryResponse {
	'soapenv:Envelope': SoapenvEnvelope;
}

export interface SoapenvEnvelope {
	$: SoapenvEnvelopeClass;
	'soapenv:Header': string[];
	'soapenv:Body': SoapenvBody[];
}

export interface SoapenvEnvelopeClass {
	'xmlns:soapenv': string;
}

export interface SoapenvBody {
	IntegrationEnquiryResultMsg: IntegrationEnquiryResultMsg[];
	'soapenv:Fault': any;
}

export interface IntegrationEnquiryResultMsg {
	$: Purple;
	ResultHeader: ResultHeader[];
	IntegrationEnquiryResult: IntegrationEnquiryResult[];
}

export interface Purple {
	xmlns: string;
}

export interface IntegrationEnquiryResult {
	$: Purple;
	BalanceRecordList: BalanceRecordList[];
	SubscriberState: SubscriberState[];
	BillingCycleDate: BillingCycleDate[];
	SubscriberInfo: SubscriberInfo[];
	CumulativeItemList: CumulativeItemList[];
	SubAttachedInfo: SubAttachedInfo[];
	Customer: Customer[];
}

export interface BalanceRecordList {
	$: Purple;
	BalanceRecord: BalanceRecord[];
}

export interface BalanceRecord {
	BalanceDesc: string[];
	Balance: string[];
	MinMeasureId: string[];
	UnitType: string[];
	AccountType: string[];
	ExpireTime: string[];
	AccountCredit: string[];
	AccountKey: string[];
	ProductID: DPEndDate[];
}

export interface DPEndDate {
	$: { [key: string]: string };
}

export interface BillingCycleDate {
	$: Purple;
	BillCycleOpenDate: string[];
	BillCycleEndDate: string[];
	BillCycleType: string[];
}

export interface CumulativeItemList {
	$: Purple;
	CumulativeItem: CumulativeItem[];
}

export interface CumulativeItem {
	CumulateID: string[];
	CumulateBeginTime: string[];
	CumulateEndTime: string[];
	CumulativeAmt: string[];
}

export interface Customer {
	$: Purple;
	Name: string[];
	Code: string[];
	Birthday: string[];
	Address: string[];
	Grade: string[];
	CustomerType: string[];
	CustomerState: string[];
}

export interface SubAttachedInfo {
	$: Purple;
	LoanLateFee: string[];
	LoanDueDate: string[];
	ChgMainProductTimes: string[];
	ChgMainPackageTimes: string[];
}

export interface SubscriberInfo {
	$: Purple;
	Subscriber: Subscriber[];
	Product: Product[];
	Service: Service[];
}

export interface Product {
	Id: string[];
	ProductOrderKey: string[];
	EffectiveDate: string[];
	ExpiredDate: string[];
	Status: string[];
}

export interface Service {
	Id: string[];
	Status: string[];
	RegistrationTime: string[];
}

export interface Subscriber {
	Code: string[];
	BrandId: string[];
	RegistrationTime: string[];
	Lang: string[];
	SMSLang: string[];
	USSDLang: string[];
	PaidMode: string[];
	InitialCredit: DPEndDate[];
	BelToAreaID: DPEndDate[];
	MainProductID: string[];
	SimpleProperty: SimpleProperty[];
	IMSI: string[];
}

export interface SimpleProperty {
	Id: string[];
	Value: string[];
}

export interface SubscriberState {
	$: Purple;
	FirstActiveDate: string[];
	ActiveCAC: string[];
	ActiveStop: string[];
	SuspendStop: string[];
	DisableStop: string[];
	LifeCycleState: string[];
	DPFlag: string[];
	FraudState: string[];
	LossFlag: string[];
	POSUserState: DPEndDate[];
	LockedFlag: string[];
	DPEndDate: DPEndDate[];
	ETUFraudState: string[];
	Oldbalance: string[];
}

export interface ResultHeader {
	$: Purple;
	CommandId: CommandID[];
	Version: CommandID[];
	TransactionId: TransactionID[];
	SequenceId: CommandID[];
	ResultCode: CommandID[];
	ResultDesc: CommandID[];
}

export interface CommandID {
	_: string;
	$: Purple;
}

export interface TransactionID {
	$: Purple;
}

export interface Cbs {
	cummulativeItemList: CumulativeItemList[];
	balanceRecordList: BalanceRecordList[];
}
