// Generated by https://quicktype.io

export interface SubscribeAppendantProductResponse {
	'soapenv:Envelope': SoapenvEnvelope;
}

export interface SoapenvEnvelope {
	$: SoapenvEnvelopeClass;
	'soapenv:Header': string[];
	'soapenv:Body': SoapenvBody[];
}

export interface SoapenvEnvelopeClass {
	'xmlns:soapenv': string;
}

export interface SoapenvBody {
	SubscribeAppendantProductResultMsg: SubscribeAppendantProductResultMsgElement[];
}

export interface SubscribeAppendantProductResultMsgElement {
	$: SubscribeAppendantProductResultMsg;
	ResultHeader: ResultHeader[];
}

export interface SubscribeAppendantProductResultMsg {
	xmlns: string;
}

export interface ResultHeader {
	$: SubscribeAppendantProductResultMsg;
	CommandId: CommandID[];
	Version: CommandID[];
	TransactionId: CommandID[];
	SequenceId: CommandID[];
	ResultCode: CommandID[];
	ResultDesc: CommandID[];
}

export interface CommandID {
	_: string;
	$: SubscribeAppendantProductResultMsg;
}
